import { useState } from 'react';
import { 
  Search, 
  Download, 
  Plus, 
  Calendar, 
  FileText 
} from 'lucide-react';
import type { Room, ServiceRequest } from '../../types';

interface ReportsProps {
  rooms: Room[];
  serviceRequests: ServiceRequest[];
}

export interface OperationalReport {
  id: string;
  name: string;
  code: string;
  category: 'HOUSEKEEPING' | 'GUEST OPS' | 'RESERVATION' | 'SERVICE' | 'F&B';
  generatedBy: string;
  dateRange: string;
  status: 'VERIFIED' | 'PROCESSING' | 'NEEDS REVIEW';
  totalItems: number;
  incidents: number;
}

export default function ReportsManagement({ rooms, serviceRequests }: ReportsProps) {
  const [reports, setReports] = useState<OperationalReport[]>([
    {
      id: 'REP-2026-001',
      name: 'Daily Housekeeping Audit',
      code: '#REP-2026-001',
      category: 'HOUSEKEEPING',
      generatedBy: 'Maria G.',
      dateRange: 'Oct 24 - Oct 25',
      status: 'VERIFIED',
      totalItems: 1482,
      incidents: 24
    },
    {
      id: 'REP-2026-002',
      name: 'Guest Satisfaction Index',
      code: '#REP-2026-002',
      category: 'GUEST OPS',
      generatedBy: 'Sarah L.',
      dateRange: 'Oct 01 - Oct 24',
      status: 'PROCESSING',
      totalItems: 840,
      incidents: 3
    },
    {
      id: 'REP-2026-003',
      name: 'Occupancy Forecast Q2',
      code: '#REP-2026-003',
      category: 'RESERVATION',
      generatedBy: 'James W.',
      dateRange: 'Oct 01 - Dec 31',
      status: 'VERIFIED',
      totalItems: 310,
      incidents: 12
    },
    {
      id: 'REP-2026-004',
      name: 'Maintenance Backlog Analysis',
      code: '#REP-2026-004',
      category: 'SERVICE',
      generatedBy: 'John D.',
      dateRange: 'Oct 15 - Oct 22',
      status: 'NEEDS REVIEW',
      totalItems: 95,
      incidents: 8
    },
    {
      id: 'REP-2026-005',
      name: 'Food & Beverage Revenue Audit',
      code: '#REP-2026-005',
      category: 'F&B',
      generatedBy: 'Nina S.',
      dateRange: 'Oct 01 - Oct 25',
      status: 'VERIFIED',
      totalItems: 670,
      incidents: 4
    }
  ]);

  const [selectedReportId, setSelectedReportId] = useState<string>('REP-2026-001');
  const [activeCategoryTab, setActiveCategoryTab] = useState<'All' | 'HOUSEKEEPING' | 'GUEST OPS' | 'RESERVATION' | 'SERVICE' | 'F&B'>('All');
  const [dateRange, setDateRange] = useState('Oct 01, 2026 - Oct 31, 2026');
  const [searchQuery, setSearchQuery] = useState('');

  const activeReport = reports.find(r => r.id === selectedReportId) || reports[0] || null;

  // Filter reports
  const filteredReports = reports.filter(r => {
    const matchesCategory = activeCategoryTab === 'All' ? true : r.category === activeCategoryTab;
    const matchesSearch = r.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          r.code.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const handleGenerateReport = () => {
    alert(`Laporan Baru Berhasil Dibuat untuk Rentang Tanggal:\n${dateRange}\nMenyiapkan file download...`);
    const newId = `REP-2026-00${reports.length + 1}`;
    const newReport: OperationalReport = {
      id: newId,
      name: `Ad-hoc Operational Audit (${dateRange.split(' - ')[0]})`,
      code: `#REP-2026-00${reports.length + 1}`,
      category: activeCategoryTab === 'All' ? 'RESERVATION' : activeCategoryTab,
      generatedBy: 'Budi Santoso',
      dateRange: 'Oct 01 - Oct 31',
      status: 'VERIFIED',
      totalItems: 450,
      incidents: 2
    };
    setReports(prev => [newReport, ...prev]);
    setSelectedReportId(newId);
  };

  const handleDownloadReportFile = (rep: OperationalReport) => {
    const csvContent = `Report ID,Report Name,Category,Generated By,Date Range,Status,Total Items,Incidents\n${rep.code},"${rep.name}",${rep.category},${rep.generatedBy},${rep.dateRange},${rep.status},${rep.totalItems},${rep.incidents}\n`;
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `${rep.name.toLowerCase().replace(/\s+/g, '_')}_${rep.id}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Real-time calculations
  const dirtyCount = rooms.filter(r => r.status === 'dirty').length;
  const activeCSRequests = serviceRequests.filter(r => r.status !== 'Resolved').length;
  const occupiedCount = rooms.filter(r => r.status === 'occupied').length;

  return (
    <div className="space-y-6 text-left">
      {/* HEADER SECTION */}
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between pb-4 border-b border-gray-200 gap-4">
        <div>
          <h2 className="text-xl font-extrabold text-[#1E3A5F]">Laporan & Audit Operasional</h2>
          <p className="text-xs text-gray-500 mt-1">SMA PERHOTELAN • Analisis Okupansi, Kinerja Staf & Layanan Tamu</p>
        </div>
        
        {/* Date range & Generate report side-by-side */}
        <div className="flex items-center gap-3 w-full lg:w-auto">
          <div className="flex items-center space-x-2 bg-gray-50 border border-gray-300 rounded-lg px-3 py-1.5 text-xs font-bold text-gray-700">
            <Calendar className="w-3.5 h-3.5 text-[#1E3A5F]" />
            <select
              value={dateRange}
              onChange={(e) => setDateRange(e.target.value)}
              className="bg-transparent focus:outline-none cursor-pointer font-semibold text-gray-750"
            >
              <option value="Oct 01, 2026 - Oct 31, 2026">01 Oct 2026 - 31 Oct 2026</option>
              <option value="Nov 01, 2026 - Nov 30, 2026">01 Nov 2026 - 30 Nov 2026</option>
              <option value="Dec 01, 2026 - Dec 31, 2026">01 Dec 2026 - 31 Dec 2026</option>
            </select>
          </div>

          <button
            onClick={handleGenerateReport}
            className="px-4 py-2 bg-[#1E3A5F] hover:bg-[#152a45] text-white text-xs font-extrabold rounded-lg flex items-center space-x-1.5 cursor-pointer shadow-sm transition-colors w-full sm:w-auto justify-center"
          >
            <Plus className="w-4 h-4" />
            <span>Generate Report</span>
          </button>
        </div>
      </div>

      {/* KPI STATS ROW */}
      <div className="grid grid-cols-2 md:grid-cols-6 gap-3">
        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-3xs">
          <p className="text-[9px] font-bold text-gray-400 uppercase">Reservations</p>
          <div className="flex justify-between items-end mt-1.5">
            <h4 className="text-xl font-extrabold text-gray-800">412</h4>
            <span className="text-[10px] text-green-500 font-bold font-sans">▲ 12%</span>
          </div>
        </div>

        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-3xs">
          <p className="text-[9px] font-bold text-gray-400 uppercase">Active Guests</p>
          <div className="flex justify-between items-end mt-1.5">
            <h4 className="text-xl font-extrabold text-gray-800">{120 + occupiedCount}</h4>
            <span className="text-[10px] text-green-500 font-bold font-sans">▲ 8%</span>
          </div>
        </div>

        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-3xs">
          <p className="text-[9px] font-bold text-gray-400 uppercase">F&B Revenue</p>
          <div className="flex justify-between items-end mt-1.5">
            <h4 className="text-md font-black text-green-700">Rp 12.8M</h4>
            <span className="text-[9px] text-green-600 font-bold font-sans">▲ 15%</span>
          </div>
        </div>

        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-3xs">
          <p className="text-[9px] font-bold text-gray-400 uppercase">F&B Sold Items</p>
          <div className="flex justify-between items-end mt-1.5">
            <h4 className="text-xl font-extrabold text-gray-800">1,280</h4>
            <span className="text-[9px] text-blue-500 font-bold font-sans">Menu</span>
          </div>
        </div>

        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-3xs">
          <p className="text-[9px] font-bold text-gray-400 uppercase">Dirty Rooms</p>
          <div className="flex justify-between items-end mt-1.5">
            <h4 className="text-xl font-extrabold text-gray-800">{dirtyCount}</h4>
            <span className="text-[9px] text-orange-500 font-bold font-sans">Kamar</span>
          </div>
        </div>

        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-3xs">
          <p className="text-[9px] font-bold text-gray-400 uppercase">Svc Requests</p>
          <div className="flex justify-between items-end mt-1.5">
            <h4 className="text-xl font-extrabold text-gray-800">{activeCSRequests}</h4>
            <span className="text-[9px] text-blue-500 font-bold font-sans">Aktif</span>
          </div>
        </div>
      </div>

      {/* TWO COLUMN GRID */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* LEFT COLUMN: OPERATIONAL REPORTS */}
        <div className="lg:col-span-8 bg-white border border-gray-200 rounded-xl overflow-hidden shadow-3xs">
          <div className="px-5 py-4 border-b border-gray-200 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div className="flex items-center space-x-3">
              <h3 className="text-sm font-extrabold text-[#1E3A5F] uppercase tracking-wider">Operational Reports</h3>
              
              {/* Category tabs */}
              <div className="flex items-center gap-1 bg-gray-100 p-0.5 rounded-lg text-[10px]">
                {(['All', 'RESERVATION', 'GUEST OPS', 'HOUSEKEEPING', 'SERVICE', 'F&B'] as const).map(cat => (
                  <button
                    key={cat}
                    onClick={() => setActiveCategoryTab(cat)}
                    className={`px-2 py-0.5 font-bold rounded cursor-pointer transition-colors ${
                      activeCategoryTab === cat ? 'bg-[#1E3A5F] text-white shadow-xs' : 'text-gray-500 hover:text-gray-800'
                    }`}
                  >
                    {cat === 'All' ? 'All' : cat}
                  </button>
                ))}
              </div>
            </div>

            {/* Filter Search */}
            <div className="relative">
              <Search className="w-3 h-3 absolute left-2.5 top-1/2 -translate-y-1/2 text-gray-400" />
              <input
                type="text"
                placeholder="Filter ledger..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-8 pr-2.5 py-1 w-full sm:w-40 bg-white border border-gray-300 rounded-lg text-[11px] font-semibold placeholder-gray-400 text-gray-800 focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="bg-gray-50 text-gray-400 font-bold uppercase tracking-wider border-b border-gray-200">
                  <th className="px-5 py-3 text-[10px]">REPORT NAME & ID</th>
                  <th className="px-5 py-3 text-[10px]">CATEGORY</th>
                  <th className="px-5 py-3 text-[10px]">GENERATED BY</th>
                  <th className="px-5 py-3 text-[10px]">DATE RANGE</th>
                  <th className="px-5 py-3 text-[10px]">STATUS</th>
                  <th className="px-5 py-3 text-[10px] text-center">ACTIONS</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-150">
                {filteredReports.map(rep => {
                  const isSelected = activeReport && rep.id === activeReport.id;
                  return (
                    <tr
                      key={rep.id}
                      onClick={() => setSelectedReportId(rep.id)}
                      className={`cursor-pointer transition-all hover:bg-gray-50/75 ${
                        isSelected ? 'bg-blue-50/45 border-l-4 border-blue-500' : ''
                      }`}
                    >
                      <td className="px-5 py-3.5">
                        <div className="font-extrabold text-[#1E3A5F]">{rep.name}</div>
                        <div className="text-[10px] text-gray-400 font-semibold mt-0.5">{rep.code}</div>
                      </td>
                      <td className="px-5 py-3.5">
                        <span className={`px-2 py-0.5 rounded text-[9px] font-black border ${
                          rep.category === 'HOUSEKEEPING' ? 'bg-orange-50 text-orange-655 border-orange-200' :
                          rep.category === 'GUEST OPS' ? 'bg-purple-50 text-purple-655 border-purple-200' :
                          rep.category === 'RESERVATION' ? 'bg-blue-50 text-blue-655 border-blue-200' :
                          rep.category === 'F&B' ? 'bg-green-50 text-green-755 border-green-200' :
                          'bg-yellow-50 text-yellow-655 border-yellow-200'
                        }`}>
                          {rep.category}
                        </span>
                      </td>
                      <td className="px-5 py-3.5">
                        <div className="flex items-center space-x-2">
                          <div className="w-5 h-5 bg-[#1E3A5F] text-white rounded-full flex items-center justify-center text-[9px] font-black uppercase">
                            {rep.generatedBy.charAt(0)}
                          </div>
                          <span className="font-bold text-gray-700">{rep.generatedBy}</span>
                        </div>
                      </td>
                      <td className="px-5 py-3.5 font-semibold text-gray-600">
                        {rep.dateRange}
                      </td>
                      <td className="px-5 py-3.5">
                        <span className="flex items-center space-x-1.5 font-bold">
                          <span className={`w-1.5 h-1.5 rounded-full ${
                            rep.status === 'VERIFIED' ? 'bg-green-500' :
                            rep.status === 'PROCESSING' ? 'bg-orange-500' :
                            'bg-red-500'
                          }`} />
                          <span className={
                            rep.status === 'VERIFIED' ? 'text-green-600' :
                            rep.status === 'PROCESSING' ? 'text-orange-600' :
                            'text-red-600'
                          }>
                            {rep.status}
                          </span>
                        </span>
                      </td>
                      <td className="px-5 py-3.5 text-center">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleDownloadReportFile(rep);
                          }}
                          className="p-1 hover:bg-gray-100 rounded text-blue-605 cursor-pointer"
                          title="Download CSV"
                        >
                          <Download className="w-3.5 h-3.5" />
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* RIGHT COLUMN: REPORT SIDEBAR */}
        <div className="lg:col-span-4 bg-white border border-gray-200 rounded-xl p-5 space-y-5 shadow-3xs text-left">
          <div className="border-b border-gray-200 pb-3">
            <h3 className="text-xs font-black text-gray-455 uppercase tracking-wider">REPORT CONTEXT</h3>
          </div>

          {activeReport ? (
            <div className="space-y-5">
              {/* Current Selection details */}
              <div className="p-4 bg-[#1E3A5F] text-white rounded-xl space-y-3">
                <div className="flex items-center space-x-2">
                  <FileText className="w-5 h-5 text-blue-200" />
                  <div>
                    <p className="text-[9px] text-blue-200 uppercase font-bold tracking-wider">CURRENT SELECTION</p>
                    <h4 className="text-xs font-extrabold">{activeReport.name}</h4>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-2 pt-2 border-t border-blue-900/60 text-center">
                  <div>
                    <p className="text-[9px] text-blue-200 uppercase">TOTAL ITEMS</p>
                    <p className="text-sm font-black mt-0.5">{activeReport.totalItems.toLocaleString()}</p>
                  </div>
                  <div>
                    <p className="text-[9px] text-blue-200 uppercase">INCIDENTS</p>
                    <p className="text-sm font-black mt-0.5 text-yellow-300">{activeReport.incidents}</p>
                  </div>
                </div>
              </div>

              {/* REPORT COMPOSITION */}
              <div className="space-y-3 border-t border-gray-150 pt-4">
                <h5 className="text-[10px] font-black text-gray-400 uppercase tracking-wider">REPORT COMPOSITION</h5>
                
                {/* SVG Donut Chart */}
                <div className="relative flex justify-center py-2">
                  <svg width="100" height="100" viewBox="0 0 36 36" className="mx-auto">
                    <circle cx="18" cy="18" r="15.915" fill="none" stroke="#F5F7FA" strokeWidth="3.5" />
                    
                    {/* Bookings segment (Navy) - 30% */}
                    <circle cx="18" cy="18" r="15.915" fill="none" stroke="#1E3A5F" strokeWidth="3.6" 
                            strokeDasharray="30 70" strokeDashoffset="100" />
                    
                    {/* Guests Managed segment (Purple) - 20% */}
                    <circle cx="18" cy="18" r="15.915" fill="none" stroke="#8B5CF6" strokeWidth="3.6" 
                            strokeDasharray="20 80" strokeDashoffset="70" />
                    
                    {/* Rooms Cleaned segment (Blue) - 20% */}
                    <circle cx="18" cy="18" r="15.915" fill="none" stroke="#3B82F6" strokeWidth="3.6" 
                            strokeDasharray="20 80" strokeDashoffset="50" />
                    
                    {/* Service Requests segment (Orange) - 15% */}
                    <circle cx="18" cy="18" r="15.915" fill="none" stroke="#F59E0B" strokeWidth="3.6" 
                            strokeDasharray="15 85" strokeDashoffset="30" />

                    {/* F&B Sales segment (Green) - 15% */}
                    <circle cx="18" cy="18" r="15.915" fill="none" stroke="#10B981" strokeWidth="3.6" 
                            strokeDasharray="15 85" strokeDashoffset="15" />
                  </svg>
                  <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                    <span className="text-[9px] font-black text-gray-800">HMS</span>
                    <span className="text-[7px] text-gray-400 font-bold uppercase tracking-wider">STATS</span>
                  </div>
                </div>

                {/* Legend with matching labels and colors */}
                <div className="grid grid-cols-2 gap-2 text-[10px] font-bold text-gray-650">
                  <div className="flex items-center space-x-1.5">
                    <span className="w-2.5 h-2.5 rounded-xs bg-[#1E3A5F]" />
                    <span>Bookings (Reservasi)</span>
                  </div>
                  <div className="flex items-center space-x-1.5">
                    <span className="w-2.5 h-2.5 rounded-xs bg-[#8B5CF6]" />
                    <span>Guests Managed</span>
                  </div>
                  <div className="flex items-center space-x-1.5">
                    <span className="w-2.5 h-2.5 rounded-xs bg-[#3B82F6]" />
                    <span>Rooms Cleaned</span>
                  </div>
                  <div className="flex items-center space-x-1.5">
                    <span className="w-2.5 h-2.5 rounded-xs bg-[#F59E0B]" />
                    <span>Service Requests</span>
                  </div>
                  <div className="flex items-center space-x-1.5 col-span-2">
                    <span className="w-2.5 h-2.5 rounded-xs bg-[#10B981]" />
                    <span>Food & Beverage Sales</span>
                  </div>
                </div>
              </div>

              {/* RECENT ACTIVITY TIMELINE */}
              <div className="space-y-3 border-t border-gray-150 pt-4">
                <h5 className="text-[10px] font-black text-gray-400 uppercase tracking-wider">RECENT ACTIVITY</h5>
                <div className="relative border-l border-gray-200 pl-4 space-y-4 ml-1.5 text-xs">
                  <div className="relative">
                    <span className="absolute -left-[21px] top-1 w-2.5 h-2.5 bg-blue-600 border border-white rounded-full" />
                    <p className="font-bold text-gray-800">Exported by Maria G.</p>
                    <p className="text-[9px] text-gray-450 font-semibold mt-0.5">Today, 10:45 AM - Excel Download</p>
                  </div>
                  <div className="relative">
                    <span className="absolute -left-[21px] top-1 w-2.5 h-2.5 bg-green-500 border border-white rounded-full" />
                    <p className="font-bold text-gray-800">Verified by Admin</p>
                    <p className="text-[9px] text-gray-455 font-semibold mt-0.5">Oct 24, 04:12 PM - Verified</p>
                  </div>
                </div>
              </div>

              {/* ACTION BUTTONS */}
              <div className="pt-2 border-t border-gray-150 flex flex-col gap-2">
                <button
                  onClick={() => alert(`Membagikan laporan ${activeReport.name} ke departemen terkait!`)}
                  className="w-full py-2 border border-gray-300 hover:bg-gray-50 text-gray-755 text-xs font-bold rounded-lg cursor-pointer transition-colors text-center shadow-3xs"
                >
                  Share with Department
                </button>
                <div className="flex gap-2">
                  <button
                    onClick={() => alert(`Penjadwalan otomatis laporan ${activeReport.name} diaktifkan!`)}
                    className="flex-1 py-2 bg-[#1E3A5F] hover:bg-[#152a45] text-white text-xs font-bold rounded-lg cursor-pointer transition-colors text-center shadow-sm"
                  >
                    Schedule
                  </button>
                  <button
                    onClick={() => handleDownloadReportFile(activeReport)}
                    className="flex-1 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-lg cursor-pointer transition-colors text-center shadow-sm"
                  >
                    Download
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <p className="text-xs text-gray-400 italic">Pilih laporan di tabel untuk melihat audit.</p>
          )}
        </div>
      </div>
    </div>
  );
}
